MODEL:
  MODEL_NAME: "FastSurferVINN"
  NUM_CLASSES: 8
  NUM_FILTERS: 71
  KERNEL_H: 3
  KERNEL_W: 3
  BASE_RES: 1.0
  OUT_TENSOR_WIDTH: 320
  OUT_TENSOR_HEIGHT: 320
  HEIGHT: 256
  WIDTH: 256

DATA:
  SIZES: [256, 311, 320]
  PADDED_SIZE: 320
  PLANE: "sagittal"
  PATH_HDF5_TRAIN: "/opt/localdata/data/usr-envs/ruiying/Code/NeurIPS/FastSurfer/FastSurfer_MAE/FastSurferCNN/train_data/training_set_sagittal.hdf5"
  PATH_HDF5_VAL: "/opt/localdata/data/usr-envs/ruiying/Code/NeurIPS/FastSurfer/FastSurfer_MAE/FastSurferCNN/train_data/val_set_sagittal.hdf5"
  AUG: ["None", "Gaussian"]

DATA_LOADER:
  NUM_WORKERS: 3

OPTIMIZER:
  LR_SCHEDULER: cosineWarmRestarts
  OPTIMIZING_METHOD: adamW

TRAIN:
  NUM_EPOCHS: 80
  BATCH_SIZE: 8
  FINE_TUNE: True
  RESUME_EXPR_NUM: "FastSurferVINN"

LOG_DIR: "/opt/localdata/data/usr-envs/ruiying/Code/NeurIPS/FastSurfer/FastSurfer_MAE/FastSurferCNN/experiments/sagittal"
EXPR_NUM: "FastSurferVINN"
MAE_MODEL: "/opt/localdata/data/usr-envs/ruiying/Code/NeurIPS/FastSurfer/FastSurfer_MAE/FastSurferCNN/MAE_Pretrain_model/model_final.pth"