name: 'Load processed data'
author: 'David Kuegler'
description: 'Load a docker image from an artifact'

inputs:
  subject-id:
    type: string
    description: "The name of the case folder"
    required: true
  subjects-dir:
    type: string
    description: "Path to the subjects-dir"
    default: "/tmp"


runs:
  using: "composite"
  steps:
    - name: Load cached subject directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.subjects-dir }}
        if [[ -d "${{ inputs.subjects-dir }}/${{ inputs.subject-id }}" ]] ; then
          echo "The expected subject directory ${{ inputs.subjects-dir }}/${{ inputs.subject-id }} already exists!"
          exit 1
        fi
    - name: Recover processed files
      uses: actions/download-artifact@v4
      with:
        name: fastsurfer-${{ github.sha }}-${{ inputs.subject-id }}
        path: ${{ inputs.subjects-dir }}/${{ inputs.subject-id }}
